sudo: false
language: objective-c
osx_image: xcode8

xcode_project: Attributed.xcodeproj
xcode_scheme: Attributed
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project Attributed.xcodeproj -scheme Attributed -sdk iphonesimulator10.0 -destination "OS=10.0,name=iPhone 5"
